# Generated by Django 5.2.5 on 2025-09-28 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'permissions': [('can_manage_blog', 'Can manage blog posts')]},
        ),
    ]
